baseurl = "https://bam6o0.github.io/planetary-scale"
title = "Planetary Scale"
languageCode = "ja-jp"
copyright = "Copyright (C) 2020- Takato Sasagawa All Right Reserved."

contentdir = "content/posts"
layoutdir = "layouts"
publishdir = "public"
pygmentsuseclasses = true
    
[indexes]
    category = "categories"

[author]
    name = "Takato Sasagawa"
    image = "bio.jpg"
    bio = "Microservices Platform Team at Mercari, Inc.. Please contact me via twitter."
    
[params]
    twitter = "bam6o0"
    github = "bam6o0"
    google_font = "Lato:900"

    [params.sharing]
        twitter =true
        
    [params.analytics]
        # googleid = ""


